ALTER TABLE about_page ADD COLUMN IF NOT EXISTS mission_text TEXT DEFAULT '';
ALTER TABLE about_page ADD COLUMN IF NOT EXISTS core_values JSONB DEFAULT '[]';
ALTER TABLE about_page ADD COLUMN IF NOT EXISTS what_we_do TEXT DEFAULT '';
ALTER TABLE about_page ADD COLUMN IF NOT EXISTS who_can_join TEXT DEFAULT '';
