ALTER TABLE site_stats ADD COLUMN IF NOT EXISTS countries INTEGER DEFAULT 0;
ALTER TABLE site_stats ADD COLUMN IF NOT EXISTS whatsapp_groups INTEGER DEFAULT 0;
ALTER TABLE site_stats ADD COLUMN IF NOT EXISTS main_channel_followers INTEGER DEFAULT 0;
ALTER TABLE site_stats ADD COLUMN IF NOT EXISTS scholarship_channel_followers INTEGER DEFAULT 0;
ALTER TABLE site_stats ADD COLUMN IF NOT EXISTS ai_channel_followers INTEGER DEFAULT 0;
